name = "rpc-proxy" # todo
main = "./src/index.ts"
compatibility_date = "2022-05-03"

[vars]
CORS_ALLOW_ORIGIN = "https://app.goosefx.io,https://app.staging.goosefx.io,http://localhost:3000,https://vesting.goosefx.io,https://nestquest.io"
